<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="49867" started-at="2019-04-19T07:47:19Z" finished-at="2019-04-19T07:48:09Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="49867" started-at="2019-04-19T07:47:19Z" finished-at="2019-04-19T07:48:09Z">
      <class name="com.pom.testcases.ChangePasswordTest">
        <test-method status="FAIL" signature="changePasswordTest(java.util.Hashtable)[pri:0, instance:com.pom.testcases.ChangePasswordTest@515c6049]" name="changePasswordTest" duration-ms="49444" started-at="2019-04-19T03:47:19Z" data-provider="getData" finished-at="2019-04-19T03:48:09Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{NewPassword=sabsah0209, Username=iusikder@yahoo.com, OldPassword=amiimtiaz, ExpectedResult=Success, Runmode=Y, Browser=Chrome}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Could not Login]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Could not Login
	at org.testng.Assert.fail(Assert.java:94)
	at com.pom.testcases.basetest.BaseTest.reportFailure(BaseTest.java:77)
	at com.pom.testcases.ChangePasswordTest.changePasswordTest(ChangePasswordTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- changePasswordTest -->
        <test-method status="PASS" signature="quit()[pri:0, instance:com.pom.testcases.ChangePasswordTest@515c6049]" name="quit" is-config="true" duration-ms="372" started-at="2019-04-19T03:48:09Z" finished-at="2019-04-19T03:48:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- com.pom.testcases.ChangePasswordTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
